machine/stompduck: Fix wic image build race condition with TF-A
The wic image generation requires trusted-firmware-a, but using
EXTRA_IMAGEDEPENDS only adds a dependency to the image_complete task,
which runs after do_image_wic. This creates a race condition where
the wic image generation may fail if the TF-A image isn't built yet.

Use WKS_FILE_DEPENDS instead to ensure trusted-firmware-a is built
before do_image_wic runs, preventing the build failure.

Fixes:

  $ bitbake -c do_image_wic kiss-image
  ...
  ERROR: kiss-image-1.0-r0 do_image_wic: ExecutionError(...)
  ...
  | wic.filemap.Error: cannot open image file '.../simplest-yocto-setup/build/tmp-glibc/deploy/images/stompduck/tf-a-stm32mp157a-dk1.stm32': [Errno 2] No such file or directory: '.../simplest-yocto-setup/build/tmp-glibc/deploy/images/stompduck/tf-a-stm32mp157a-dk1.stm32'

Signed-off-by: Kory Maincent <kory.maincent@bootlin.com>
[Luca: added steps to reproduce error to commit message]
Signed-off-by: Luca Ceresoli <luca.ceresoli@bootlin.com>